<?php
/**
 * TL_ROOT/system/modules/recaptcha/languages/cs/modules.php 
 * 
 * Contao extension: recaptcha 1.0.1 stable 
 * Czech translation file 
 * 
 * Copyright : &copy; Florian Stallmann 2013 
 * License   : GNU LGPL V3 
 * Author    : FS Informatik (mr_flory), http://fs-informatik.de 
 * Translator: Tomas Petrlik (frogzone), www.frogzone.cz 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['recaptcha']['0'] = "reCapchta";
$GLOBALS['TL_LANG']['MOD']['recaptcha']['1'] = "Vytvoří pole formuláře pro reCaptcha s bezpečnostní otázkou.";
 
?>
