<?php
/**
 * TL_ROOT/system/modules/recaptcha/languages/cs/tl_layout.php 
 * 
 * Contao extension: recaptcha 1.0.1 stable 
 * Czech translation file 
 * 
 * Copyright : &copy; Florian Stallmann 2013 
 * License   : GNU LGPL V3 
 * Author    : FS Informatik (mr_flory), http://fs-informatik.de 
 * Translator: Tomas Petrlik (frogzone), www.frogzone.cz 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_layout']['recPublicKey']['0'] = "reCaptcha Veřejný klíč";
$GLOBALS['TL_LANG']['tl_layout']['recPublicKey']['1'] = "Prosím, zadejte veřejný klíč pro reCaptcha. Pokud necháte toto pole prázdné, bude použit globální klíč. O klíč můžete požádat na <a href=\"http://www.recaptcha.net/api/getkey\">http://www.recaptcha.net/api/getkey</a>.";
$GLOBALS['TL_LANG']['tl_layout']['recPrivateKey']['0'] = "reCaptcha Soukromý klíč";
$GLOBALS['TL_LANG']['tl_layout']['recPrivateKey']['1'] = "Prosím, zadejte soukromý klíč pro reCaptcha. Pokud necháte toto pole prázdné, bude použít globální klíč. O klíč můžete požádat na <a href=\"http://www.recaptcha.net/api/getkey\">http://www.recaptcha.net/api/getkey</a>.";
$GLOBALS['TL_LANG']['tl_layout']['recTheme']['0'] = "reCaptcha Vzhled";
$GLOBALS['TL_LANG']['tl_layout']['recTheme']['1'] = "Prosím, vyberte motiv použitý pro reCaptcha. Pro vlastní motiv musíte vytvořit šablonu.";
$GLOBALS['TL_LANG']['tl_layout']['recCustomTemplate']['0'] = "reCaptcha Vlastní šablona";
$GLOBALS['TL_LANG']['tl_layout']['recCustomTemplate']['1'] = "Prosím, vyberte vlastní šablonu pro reCaptcha.";
$GLOBALS['TL_LANG']['tl_layout']['recaptcha_legend'] = "ReCaptcha nastavení";
 
?>
