<?php
/**
 * TL_ROOT/system/modules/recaptcha/languages/ru/tl_layout.php 
 * 
 * TYPOlight extension: recaptcha 0.3.1 stable 
 * Russian translation file 
 * 
 * Copyright : &copy; Florian Stallmann 2008 
 * License   : GNU LGPL V3 
 * Author    : Florian Stallmann (mr_flory), http://fs-informatik.de 
 * Translator: Dmitry Kuznetsov (kuzmich), http://on.freedom-vrn.ru 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_layout']['recPublicKey']['0'] = "Публичный ключ reCaptcha";
$GLOBALS['TL_LANG']['tl_layout']['recPublicKey']['1'] = "Пожалуйста, введите публичный ключ reCaptcha. Вы можете получить его на <a href=\"http://www.recaptcha.net/api/getkey\">http://www.recaptcha.net/api/getkey</a>.";
$GLOBALS['TL_LANG']['tl_layout']['recPrivateKey']['0'] = "Частный ключ reCaptcha";
$GLOBALS['TL_LANG']['tl_layout']['recPrivateKey']['1'] = "Пожалуйста, введите частный ключ reCaptcha. Вы можете получить его на <a href=\"http://www.recaptcha.net/api/getkey\">http://www.recaptcha.net/api/getkey</a>.";
$GLOBALS['TL_LANG']['tl_layout']['recTheme']['0'] = "Тема reCaptcha";
$GLOBALS['TL_LANG']['tl_layout']['recTheme']['1'] = "Пожалуйста, выберите тему, используемую в reCaptcha. Для пользовательских тем, нужно создать шаблон.";
$GLOBALS['TL_LANG']['tl_layout']['recCustomTemplate']['0'] = "reCaptcha Custom Template";
$GLOBALS['TL_LANG']['tl_layout']['recCustomTemplate']['1'] = "Please choose the Custom Template used by reCaptcha.";
$GLOBALS['TL_LANG']['tl_layout']['recaptcha_legend']    = "ReCaptcha settings";

?>
