<?php
/**
 * TL_ROOT/system/modules/recaptcha/languages/fr/default.php 
 * 
 * TYPOlight extension: recaptcha 0.3.1 stable 
 * Französisch translation file 
 * 
 * Copyright : &copy; Florian Stallmann 2008 
 * License   : GNU LGPL V3 
 * Author    : Florian Stallmann (mr_flory), http://fs-informatik.de 
 * Translator: Guéric Folliot (gueric), http://www.typolight.fr 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
#$GLOBALS['TL_LANG']['recaptcha']['missing_keys'] = "Erreur! Il n'y a pas de paire de clés dans la présentation de page.";
 
?>
