<?php
/**
 * TL_ROOT/system/modules/recaptcha/languages/fr/modules.php 
 * 
 * TYPOlight extension: recaptcha 0.3.1 stable 
 * Französisch translation file 
 * 
 * Copyright : &copy; Florian Stallmann 2008 
 * License   : GNU LGPL V3 
 * Author    : Florian Stallmann (mr_flory), http://fs-informatik.de 
 * Translator: Guéric Folliot (gueric), http://www.typolight.fr 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['recaptcha']['0'] = "reCapchta";
$GLOBALS['TL_LANG']['MOD']['recaptcha']['1'] = "Génère un champ de formulaire pour une question de sécurité reCaptcha.";
 
?>
