<?php
/**
 * TL_ROOT/system/modules/recaptcha/languages/fr/tl_form_field.php 
 * 
 * TYPOlight extension: recaptcha 0.3.1 stable 
 * Französisch translation file 
 * 
 * Copyright : &copy; Florian Stallmann 2008 
 * License   : GNU LGPL V3 
 * Author    : Florian Stallmann (mr_flory), http://fs-informatik.de 
 * Translator: Guéric Folliot (gueric), http://www.typolight.fr 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['FFL']['recaptcha']['0'] = "Question de sécurité reCaptcha";
$GLOBALS['TL_LANG']['FFL']['recaptcha']['1'] = "Ce champ ajoute un reCaptcha qui doit être répondu afin de soumettre le formulaire.";
 
?>
