<?php
/**
 * TL_ROOT/system/modules/recaptcha/languages/fr/tl_layout.php 
 * 
 * TYPOlight extension: recaptcha 0.3.1 stable 
 * Französisch translation file 
 * 
 * Copyright : &copy; Florian Stallmann 2008 
 * License   : GNU LGPL V3 
 * Author    : Florian Stallmann (mr_flory), http://fs-informatik.de 
 * Translator: Guéric Folliot (gueric), http://www.typolight.fr 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_layout']['recPublicKey']['0'] = "Clé publique reCaptcha";
$GLOBALS['TL_LANG']['tl_layout']['recPublicKey']['1'] = "Veuillez entrer la clé publique pour reCaptcha. \nVous pouvez demander un paire de clés sur <a href=\"http://www.recaptcha.net/api/getkey\">http://www.recaptcha.net/api/getkey</a>.";
$GLOBALS['TL_LANG']['tl_layout']['recPrivateKey']['0'] = "Clé privée reCaptcha";
$GLOBALS['TL_LANG']['tl_layout']['recPrivateKey']['1'] = "Veuillez entrer la clé privée pour reCaptcha. \nVous pouvez demander un paire de clés sur <a href=\"http://www.recaptcha.net/api/getkey\">http://www.recaptcha.net/api/getkey</a>.";
$GLOBALS['TL_LANG']['tl_layout']['recTheme']['0'] = "Thème reCaptcha";
$GLOBALS['TL_LANG']['tl_layout']['recTheme']['1'] = "Veuillez choisir le thème utilisé par reCaptcha. Pour avoir un thème personnalisé, vous devez créer un modèle.";
$GLOBALS['TL_LANG']['tl_layout']['recCustomTemplate']['0']      = "Modèle reCaptcha";
$GLOBALS['TL_LANG']['tl_layout']['recCustomTemplate']['1']      = "Veuillez choisir le modèle utilisé par reCaptcha.";
$GLOBALS['TL_LANG']['tl_layout']['recaptcha_legend']    = "ReCaptcha settings";

?>
